# -*- coding: utf-8 -*-
"""MI_5_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vge3NtPtzNhzXpcYgYX5DqvsEC1BXWC4
"""

from numpy import array,random,dot
import matplotlib.pyplot as plt

hardlim = lambda x: 0 if x < 0 else 1

training_data = array([
                      [1,
                       1,0,1, #H
                       1,1,1,
                       1,0,1],
                      [1,
                       0,1,0, #I
                       0,1,0,
                       0,1,0]])

result = array([[1,0],[0,1]])

def perceptron_learning(data,result):
  lr = .01
  E = 1
  N, n = data.shape
  w1 = random.randn(n, 1)
  w2 = random.randn(n, 1)
  while E != 0:
    E = 0
    for i in range (0,N):
      yi1 = hardlim(dot(data[i], w1))
      yi2 = hardlim(dot(data[i], w2))
      ei1 = result[i][0] - yi1
      ei2 = result[i][1] - yi2
     
      w1 = w1 + lr * ei1 * data[i].reshape(n, 1)
      w2 = w2 + lr * ei2 * data[i].reshape(n, 1)
      E = E + ei1 ** 2
      E = E + ei2 ** 2
  #print(w1,w2)

perceptron_learning(training_data, result)

